{"name": "Запрос PUT \"Принять заказ\" для заказа с некорректным id заказа", "status": "passed", "steps": [{"name": "Отправка запроса PUT: Принятие заказа с id \"8378682\", id курьера \"367031\", ожидается сообщение: \"Заказа с таким id не существует\" с кодом \"404\"", "status": "passed", "start": 1723400712328, "stop": 1723400712429}], "parameters": [{"name": "order_id", "value": "8378682"}, {"name": "error_code", "value": "404"}, {"name": "error_message", "value": "'Заказа с таким id не существует'"}], "start": 1723400712328, "stop": 1723400712430, "uuid": "50f68d6b-4a00-47e4-8798-5a4b72a9d569", "historyId": "ae3238fb0fb11ea89852a1586e26df82", "testCaseId": "45ad7cfa7a3427bc4cb266b1ad3db1ba", "fullName": "test.test_take_order.TestTakeOrder#test_take_order_invalid_order_id_error_invalid_data", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_take_order"}, {"name": "subSuite", "value": "TestTakeOrder"}, {"name": "host", "value": "MacBook-Air-Elizaveta.local"}, {"name": "thread", "value": "16582-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_take_order"}]}